name: CI

on: [push, workflow_dispatch]
env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [20.x]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Cypress Tests
        run: npx cypress run --browser chrome --record --group "pipeline-${{ github.run_id }}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: videos
          path: cypress/videos
