name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
env:
  CYPRESS_RECORD_KEY: "581d26a9-18a7-471a-a53d-d3c2149dd2cb"
  CYPRESS_PROJECT_ID: "2d23sb"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run cy_run
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
